### PR TITLE
issue:fix for issue #690 - incorrect computation of n

### PR DESCRIPTION
**Pull request by StatKumar**
This is the fix for the issue # 690. 

Math error was occurring when the len(n) = 1. While slicing the array, the last value of the array is not considered, and due to slicing, a variable's value was set to 0, and later in the code, log of that variable was taken, which led to math error. 

Fix:
n = np.sum(~missing[firstnonmiss:lastnonmiss]) 
changed to
n = np.sum(~missing[firstnonmiss:])

### CODE REVIEW

**Comment by jmoralez** [comment]
Hey @StatKumar. Can you please:
* Read the [contributing guidelines](https://github.com/Nixtla/statsforecast/blob/main/CONTRIBUTING.md) and make the change in the notebook.
* Make the change I suggested [here](https://github.com/Nixtla/statsforecast/issues/690#issuecomment-1824642237) (`lastnonmiss = missing_idxs.max() + 1`). The proposed change here would unnecessarily break the code for people who are directly using the AutoARIMA model and passing arrays like [nan, 1, 2, 3, nan].
* Also change the other places where this is happening, which I referenced [here](https://github.com/Nixtla/statsforecast/issues/690#issuecomment-1824642237) as well.

**Comment by StatKumar** [comment]
@jmoralez Thank you for the guidelines. Will update soon.

**Comment by jmoralez** [comment]
Can you update this PR instead of opening a new one?

**Comment by StatKumar** [comment]
Sure @jmoralez

**Comment by StatKumar** [comment]
@jmoralez Updated the pull request with a new commit. Please let me know if anything else needs to be done. Thank you for taking time in guiding me through my first issue in statsforecast.

**Comment by jmoralez** [comment]
Thanks @StatKumar! This also happens in the `myarima` function. Can you add the fix there as well? Also please add a cell at the bottom with the original example from #690 (`AutoARIMA().fit(np.array([1.0]))`) to make sure that the fix works.

**Review by jmoralez — APPROVED** [review]

**Pull request merged**
