### PR TITLE
Restructure of development environment

### PR DESCRIPTION
**Pull request by akmalsoliev**
At current moment, reconstruction of development environment can throw multiple errors in rebuilding process and forces the developer to use Conda.
The error is usually thrown by Prophet on Mac, haven't had an issue on Linux (specifically Debian/Ubuntu).
Docker fixes that issue and environment recreation is much faster process.

`Makefile` will serve as navigator and development workstation setup. All commands have been tested and work without any issues.

Docker files are nested in dev directory.

Issues:
`Dockerfile-Conda` requires significant GB of ram. After multiple trial and errors it has come to my attention that 8GB is ideal. This is not the case with `Dockerfile` that installs all the requirements in much faster time and does not require significant GB of ram.

### CODE REVIEW

**Review by FedericoGarza — CHANGES_REQUESTED** [review]
Hi @akmalsoliev! 

Thank you for this! Really nice.

I have a couple of comments:

- I noticed a typo in the `dev/environment.yml` file (`envioronment.yml` instead of `environment.yml`).
- Could we add the new location of the environment file in `.github/workflows/ci.yaml`? (For the tests to run correctly.) Adding `environment-file: dev/environment.yml` here:
https://github.com/Nixtla/statsforecast/blob/dc900bdefba5ea42b6cfef9d567a29b2df970549/.github/workflows/ci.yaml#L47-L51 should work. 

- Finally, could we update the [CONTRIBUTING.md](https://github.com/Nixtla/statsforecast/blob/main/CONTRIBUTING.md) file to reflect the changes? 

Thank you!

**Comment by akmalsoliev** [comment]
@FedericoGarza glad to help! 

Adding the commit message to conversation for ease of review: 

Adapted the changes and changed used files
1. Fixed the typo
2. Added environment to `ci.yaml`
3. Changed the `CONTRIBUTING.md` to include the Docker alternatives

Additional changes:
* Removed the `Makefile` that was in `dev` directory; should of been
  removed earlier.
* `Makefile` now contains `buildless` that will run the container
  without building the image. Made in case if the image is already
  cached.
* Removed `Dockerfile-Conda`; was used for debugging and does not hold
  value moving forward; it is very error prone, so if kept moving
  forward should pass through more adjustments. Would require changing
  available RAM on Docker client.

**Comment by akmalsoliev** [comment]
Hey @FedericoGarza, 
I've added the `environment-file` to both tests as requested, please let me know if this does the job. 
Thx

**Review by FedericoGarza — APPROVED** [review]

**Comment by FedericoGarza** [comment]
Thank you @akmalsoliev! :)

**Comment by FedericoGarza** [comment]
@all-contributors please add @akmalsoliev as contributor for code

**Pull request merged**
