### PR TITLE
[Core] Fixed RuntimeWarning Generated by _get_cols (#538)

### LINKED ISSUE #538: [Core] RuntimeWarning Generated by _get_cols
### What happened + What you expected to happen

Running StatsForecast forecast results in a warning:

```
<__array_function__ internals>:200: RuntimeWarning: invalid value encountered in cast
```

Minimum example:

```python
from statsforecast.core import StatsForecast
from statsforecast.models import ( 
    AutoETS,
)
from statsforecast.utils import generate_series

n_series = 4
horizon = 7

series = generate_series(n_series)

models = [
    AutoETS(season_length=7),
    ]

sf = StatsForecast(
    models=models,
    freq='D',
)
sf.forecast(df=series, h=horizon).head()
```

The warnings points to [this line](https://github.com/Nixtla/statsforecast/blob/main/statsforecast/core.py#L81) in core that uses `np.full()`. The error is because we can't use `np.intXX` as the `dtype` when `np.nan` is the fill value since `np.nan` is a float.

We can maybe change the fill value since it gets replaced. Not sure yet on the impact.

### Versions / Dependencies

statsforecast==1.5.0
pandas==1.5.3
numpy==1.24.0

### Reproduction script

To reproduce the warning:
```python
import numpy as np
np.full((2, 2), np.nan, dtype=np.int64)
```

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by taniishkaaa**
Fixes #538

### CODE REVIEW

**Comment by taniishkaaa** [comment]
hi @kvnkho im having trouble installing the libraries within the `environment.yml` file. It produces the following error:
`Command 'mamba' not found, did you mean:
  command 'samba' from deb samba (2:4.15.13+dfsg-0ubuntu1.1)
Try: sudo apt install <deb name>`
Can you help me resolve this issue?

**Comment by kvnkho** [comment]
Sorry late reply @taniishkaaa , I think you shouldn't need mamba to install the dependencies. On your fork if you clone the repo, you can navigate to the root of the directory and do:

```
pip install -e .
```

If you have pip available. If you use conda, you can run the pip install inside a new environment.

**Comment by kvnkho** [comment]
@taniishkaaa , I see you already changed the code in the right notebook. We're nearly there.

Just run `nbdev_export` to generate the .py file from the change to the notebook. Note you need nbdev installed for this.

Also, it looks like his branch now just has merge conflicts due to the changes in master. I think you merged rather than rebased? It might be easiest if you just branched off the new main again and did these changes. I can hop on a call and help you with that if you want.

**Comment by kvnkho** [comment]
Could you give me access to your fork? https://github.com/taniishkaaa/statsforecast/ . I think I can fix it also.

**Comment by kvnkho** [comment]
@taniishkaaa , we did it! Just needed to merge the master into your branch and run `nbdev_export`.

Thanks for the contribution! I'll let the tests pass and then I'll accept this and merge it in.

**Review by kvnkho — APPROVED** [review]

**Comment by taniishkaaa** [comment]
> @taniishkaaa , we did it! Just needed to merge the master into your branch and run `nbdev_export`.
> 
> Thanks for the contribution! I'll let the tests pass and then I'll accept this and merge it in.

yay! Thanks for all your help. lmk if I can help contribute some more

**Pull request merged**
