### PR TITLE
Isolated import cells [Issue #653]

### PR DESCRIPTION
**Pull request by patrick-dd**
Addressing issue #653 

Have isolated input cells for all notebooks that require isolation.

All unmodified notebooks in the list on [this page](https://github.com/Nixtla/statsforecast/issues/653) don't require work.

### CODE REVIEW

**Comment by jmoralez** [comment]
Hey @patrick-dd, thanks a lot for working on this! I just have a small request, if the original cell has a `#| hide` in it, can you please make sure that the new cell with the imports also has it? I see you carried them over in some of the cells but not all.

**Comment by patrick-dd** [comment]
@jmoralez can do

**Comment by patrick-dd** [comment]
I believe that should do it

**Comment by jmoralez** [comment]
This is awesome! You can see the time to build the docs went down from almost 6 minutes ([yesterday's run](https://github.com/Nixtla/statsforecast/actions/runs/6814607920/job/18531856644)) to around 2.5 minutes in [this PR](https://github.com/Nixtla/statsforecast/actions/runs/6827837478/job/18570895401?pr=691). Also all the warnings are gone. Thanks a lot for this!

**Review by jmoralez — APPROVED** [review]

**Pull request merged**
