### PR TITLE
[FEATURE] Polars support

### PR DESCRIPTION
**Pull request by akmalsoliev**
`generate_series` was creating issues, as polars does not like importing categorical values from pandas; hence had to recreate the series (DataFrame) generator.

* Additionally, improved the build time: 

________________________________________________________ 
before:
________________________________________________________
Executed in    3.93 secs    fish           external
   usr time    4.68 secs    0.06 millis    4.68 secs
   sys time    1.44 secs    1.03 millis    1.43 secs

________________________________________________________ 
after:
________________________________________________________
Executed in  833.23 millis    fish           external
   usr time    2.23 secs      0.07 millis    2.23 secs
   sys time    0.50 secs      1.20 millis    0.50 secs
________________________________________________________

* `.gitignore` contains `.venv`

* Added `polars` to `environment.yml` and `requirements.txt`

* Fixed minor aspect of Makefile

### CODE REVIEW

**Comment by akmalsoliev** [comment]
@FedericoGarza any reason why these tests are failing? everything seems to work fine

**Comment by akmalsoliev** [comment]
@FedericoGarza Could I ask you to provide insight on the failed test?

**Comment by FedericoGarza** [comment]
Hey @akmalsoliev! It seems strange; let me dig into it :)

**Comment by akmalsoliev** [comment]
@FedericoGarza I believe that this is the last iteration of the modifications I will be making to this codebase, as the only aspect that's left is the implementation of tests, to see if the DataFrames have been converted correctly, however, adding tests for that will create further complications as it will just reiterate the same tests that are applied to pandas DataFrames.

**Comment by akmalsoliev** [comment]
# Complete

-[✅] Addition of a new class `DataFrameProcessing` 

-[✅] Created new testing for Polars DataFrame

# Summary

`DataFrameProcessing` is a modular class that takes in either Polars or Pandas DataFrame and transforms it into Numpy Array. DataFrame engine is created that will server as a universal DataFrame construct (either `pl.DataFrame` or `pd.DataFrame`)

# Included

* DataFrame validation: ensuring that all required columns are present in DataFrame.

* Maintained data structure with Numpy Structured Array; can be accessed via `DataFrameProcessing.np_df`

* Polars and Pandas produce different Strucutred Arrays, while this is not an issue for datestamp, "ds", and "unique_id" columns, it creates a significant hurdle in all value columns. For this purposes an additional check has been that transforms a single dimensional structure array that contains multiple value columns into split Structured Array with column length dimensions. Reference: line 28.

* Ensuring alignment of "unique_id" dtype: numerical test has been added that will transform "unique_id" into `float` if values are numerical.

* Dates are returned in original format: dates had to converted to `int` to match numpy array dtypes, they are later converted back. 

# TO-DO:

* Ensure that `StatsForecast` class outputs the same DataFrame type as its input.

* *Potential*: full implementation of `DataFrameProcessing` by dumping `_grouped_array_from_df`. @FedericoGarza  let me know your thoughts on that.

**Comment by akmalsoliev** [comment]
✅ Completed the DataFrame converted. Passed all local tests.

**Comment by akmalsoliev** [comment]
# Complete 

- [✅] Ensure that StatsForecast class outputs the same DataFrame type as its input.

The StatsForecast class has been updated to ensure that the output DataFrame type matches the input DataFrame. This enhancement is achieved through the following changes:

The `_make_future_df` method now generates a DataFrame using either Pandas or Polars, based on the DataFrame engine specified in the `_prepare_fit` method. Consequently, the resulting DataFrame from `_StatsForecast` will align with the input DataFrame.

It is worth noting that `_prepare_fit` involves DataFrame processing, which includes calling `_grouped_array_from_df` and `DataFrameProcessing` functions.

- [✅] Modify `.plot` staticmethod to work both with Polars and Pandas

To enhance the versatility of the `.plot` static method, modifications have been implemented to ensure compatibility with both Polars and Pandas. Unfortunately, the method heavily relies on Pandas, which necessitates converting Polars data to Pandas. Nonetheless, improvements have been made in the declaration of `unique_ids` within the function.

**Review by FedericoGarza — CHANGES_REQUESTED** [review]
hey @akmalsoliev! Thank you very much for working on this integration. I left a couple of comments, I'm still reviewing the `DataFrameProcessing` class. Could you please generate the `.py` files from the notebooks? To do so, you have to add `#| exporti` at the beginning of the cell containing the `DataFrameProcessing` class, and after that execute the `nbdev_export` command (this will generate the `core.py` and `utils.py` files inside the `statsforecast` directory).

**Review by akmalsoliev — COMMENTED** [review]
[✅] cleared output and exported .py

**Review by FedericoGarza — APPROVED** [review]
Thank you @akmalsoliev! Awesome feature! :)

**Pull request merged**
