### PR TITLE
fix: auto arima xreg rank deficient test

### PR DESCRIPTION
**Pull request by andrewscottm**
Corrects auto arima "xreg is rank deficient" test, as raised in https://github.com/Nixtla/statsforecast/issues/902

### CODE REVIEW

**Comment by jmoralez** [comment]
Thanks! Can you please do this instead?

```python
X = np.hstack([np.ones([xregg.shape[0], 1]), xregg])
```

**Comment by andrewscottm** [comment]
> Thanks! Can you please do this instead?
> 
> ```python
> X = np.hstack([np.ones([xregg.shape[0], 1]), xregg])
> ```

Done. yes, that's simpler

**Review by jmoralez — APPROVED** [review]
Thanks!

**Comment by jmoralez** [comment]
@andrewscottm can you please sign the CLA? Once that's done this should be automatically merged.

**Comment by andrewscottm** [comment]
> @andrewscottm can you please sign the CLA? Once that's done this should be automatically merged.

Thanks. Will do. CLA is fine but it might take another week before I can sign

**Comment by blackhole-canada** [comment]
Hello :) I am still getting an error. Is the fix implemented in the main branch or I have to pull from some another branch!

**Comment by andrewscottm** [comment]
Yes, it's in the main branch. You could check you have the fix with, eg., `print(inspect.getsource(statsforecast.arima.auto_arima_f))`

**Comment by blackhole-canada** [comment]
> Yes, it's in the main branch. You could check you have the fix with, eg., `print(inspect.getsource(statsforecast.arima.auto_arima_f))`

Sorry, I am new to it. How do I know if I have the fix from the output of `print(inspect.getsource(statsforecast.arima.auto_arima_f))`

**Comment by andrewscottm** [comment]
The [change](https://github.com/Nixtla/statsforecast/pull/931/files) is in that function. Please just check you have it. If not, then you likely haven't installed the updated base branch

**Pull request merged**
