### PR TITLE
[FIX] #623

### PR DESCRIPTION
**Pull request by akmalsoliev**
All indexes will be reset and `unique_id` will be structured to become a single index, the rest of the indexes will be treated as columns. 

Issue link: https://github.com/Nixtla/statsforecast/issues/623

### CODE REVIEW

**Comment by jmoralez** [comment]
Hey @akmalsoliev, do you have a reproducible example of #623?

**Comment by akmalsoliev** [comment]
> Hey @akmalsoliev, do you have a reproducible example of #623?

Give this a try:
```py
import pandas as pd

Y_df = pd.read_parquet('https://datasets-nixtla.s3.amazonaws.com/m4-hourly.parquet')
Y_df = Y_df.set_index(["unique_id", "ds"])
from statsforecast import StatsForecast

StatsForecast.plot(Y_df)

from statsforecast.models import (
    HistoricAverage,
    SeasonalNaive,
)

# Create a list of models and instantiation parameters
models = [
    HistoricAverage(),
]

# Instantiate StatsForecast class as sf
sf = StatsForecast(
    df=Y_df, 
    models=models,
    freq='H', 
    n_jobs=-1,
    fallback_model = SeasonalNaive(season_length=7)
)

forecasts_df = sf.forecast(h=48, level=[90])

sf.plot(Y_df,forecasts_df)
```

**Comment by jmoralez** [comment]
Wouldn't that fail the column validation?

**Comment by akmalsoliev** [comment]
UPDATE: awaiting @mark-conway reply to fully understand the issue.

**Comment by akmalsoliev** [comment]
Depreciated in favour of a new structure.

**Pull request closed without merging**
