### PR TITLE
arima model user guide

### PR DESCRIPTION
**Pull request by Naren8520**

### CODE REVIEW

**Comment by kvnkho** [comment]
This is amazing @Naren8520! Thanks for the contribution.

I think you need to add your email to your Github account to be able to sign the License agreement: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account

Second, I saw a tqdm error in the notebook. If you want to remove it, you can Add a cell at the top like this:

```
#| hide
import warnings
warnings.simplefilter('ignore')

import logging
logging.getLogger('statsforecast').setLevel(logging.ERROR)
```

And it will hide the this cell from the HTML file. This will hide the tqdm error.

**Comment by kvnkho** [comment]
The tutorials have reorganized a bit. Could you put your file under

```
docs/tutorials/ARIMA.ipynb
```

?

**Comment by mergenthaler** [comment]
@Naren8520: a fantastic job. Thanks! 

@FedericoGarza: please share your comments on this sort of text. I'm particularly interested to know if something is missing or if the structure seems right to you. As you know, @Naren8520, has expressed to do the same for other models like ETS, MSTL, and Theta.

**Comment by kvnkho** [comment]
Note to self: check parameters of different models before approving. Some have updated.

**Comment by kvnkho** [comment]
For future reference, there is something weird with cross-validation plotting. I find this snippet is not printing anything so I will remove it for now and reinsert after investigating.

```
crossvalidation_df.rename(columns = {'y' : 'actual'}, inplace = True) # rename actual values 

cutoff = crossvalidation_df['cutoff'].unique()

for k in range(len(cutoff)): 
    cv = crossvalidation_df[crossvalidation_df['cutoff'] == cutoff[k]]
    StatsForecast.plot(df, cv.loc[:, cv.columns != 'cutoff'], engine="matplotlib")
```

**Comment by kvnkho** [comment]
I finished reviewing this but CI is failing because `seaborn` is used in a couple of these. `plotly` is also used in some. Do we need to make a development dependency file? @jmoralez

**Comment by kvnkho** [comment]
Ready to merge! @jmoralez @Naren8520

**Comment by jmoralez** [comment]
@kvnkho it's good to run these files in the CI to make sure we don't have any broken tutorials. You can add seaborn to the conda section of `dev/environment.yml` and `dev/local_environment.yml` (note that these are sorted alphabetically, so it should be added after scipy), plotly is already there so it should be fine.

**Comment by jmoralez** [comment]
@kvnkho nevermind. Seems like we don't run any of the documentation. I think you can add a `.notest` file in `docs/models` like the one [here](https://github.com/Nixtla/statsforecast/blob/main/nbs/docs/tutorials/.notest) so they're not run.

**Comment by kvnkho** [comment]
I think this should be good @FedericoGarza @Naren8520 @jmoralez. I am having problems previewing locally as I get errors in other files.

**Comment by kvnkho** [comment]
Was able to preview locally. Looks good!

**Review by jmoralez — APPROVED** [review]

**Pull request merged**
