### PR TITLE
Updating Distributed Documentation

### PR DESCRIPTION
**Pull request by kvnkho**
Addresses the following issues:

https://github.com/Nixtla/statsforecast/issues/506
https://github.com/Nixtla/statsforecast/issues/505
https://github.com/Nixtla/statsforecast/issues/466

I still need to update the M5 notebook to close the [Spark issue](https://github.com/Nixtla/statsforecast/issues/504). 

I updated the `sidebar.yml`, just let me know if that's wrong. 

The Ray notebook is a bit messy due to INFO logs, I'll look at how to silence them.

### CODE REVIEW

**Review by FedericoGarza — DISMISSED** [review]
Thank you, @kvnkho! This is nice; I liked the approach to be concise with the distributed backends. ❤️

Regarding the `sidebar.yml`, it is not necessary to modify it. Could you restore it? Thank you!

**Comment by kvnkho** [comment]
Reverted changes to sidebar and deleted the qmd files which I think are no longer needed.

**Review by FedericoGarza — APPROVED** [review]
Thank you @kvnkho!

**Comment by FedericoGarza** [comment]
@all-contributors please add [kvnkho](https://github.com/kvnkho) for code

**Comment by FedericoGarza** [comment]
@all-contributors please add @kvnkho for code

**Pull request merged**
