### PR TITLE
Add fugue example

### PR DESCRIPTION
**Pull request by goodwanghan**

### CODE REVIEW

**Comment by goodwanghan** [comment]
@FedericoGarza @mergenthaler I just added a performance experiment using Fugue + Spark/Dask because I feel this is very interesting. In the notebook, I only publicized the performance numbers on 10k serieses and 128 cpus. If you are interested we can chat more about the performance on larger datasets. I think it would be fair if you conduct the experiments.

**Comment by FedericoGarza** [comment]
Thank you @goodwanghan! And sorry for the late response. I also opened an [issue](https://github.com/Nixtla/statsforecast/issues/119) to include fugue as a native backend for StatsForecast. 

Welcome to StatsForecast :tada: :D

**Comment by FedericoGarza** [comment]
Once we have the first version, we will conduct the experiments. :)

**Comment by goodwanghan** [comment]
@FedericoGarza that sounds great, thank you!

**Pull request merged**
