### PR TITLE
fix: exogenous variables

### PR DESCRIPTION
**Pull request by FedericoGarza**

### CODE REVIEW

**Comment by jmoralez** [comment]
Haha I also worked on this

**Comment by FedericoGarza** [comment]
xD Let's use yours, I think recycling the `_grouped_array_from_df` is more readable. 👍

**Comment by jmoralez** [comment]
Should I push to this branch?

**Comment by FedericoGarza** [comment]
I think a new branch would be better. Let me close this PR. :)

**Pull request closed without merging**
