### PR TITLE
Fix SyntaxWarning: invalid escape sequence

### PR DESCRIPTION
**Pull request by ravibrock**
Python was outputting the following when I tried to import `statsforecast` via `darts`:
```
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:1819: SyntaxWarning: invalid escape sequence '\h'
  """SimpleExponentialSmoothing model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:1995: SyntaxWarning: invalid escape sequence '\h'
  """SimpleExponentialSmoothing model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:2177: SyntaxWarning: invalid escape sequence '\h'
  """SeasonalExponentialSmoothing model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:2385: SyntaxWarning: invalid escape sequence '\h'
  """SeasonalExponentialSmoothingOptimized model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:2658: SyntaxWarning: invalid escape sequence '\h'
  """HistoricAverage model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:2836: SyntaxWarning: invalid escape sequence '\h'
  """Naive model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:3064: SyntaxWarning: invalid escape sequence '\h'
  """RandomWalkWithDrift model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:4074: SyntaxWarning: invalid escape sequence '\h'
  """CrostonClassic model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:4280: SyntaxWarning: invalid escape sequence '\h'
  """CrostonOptimized model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:4454: SyntaxWarning: invalid escape sequence '\h'
  """CrostonSBA model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:4846: SyntaxWarning: invalid escape sequence '\h'
  """TSB model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:5733: SyntaxWarning: invalid escape sequence '\s'
  """Generalized Autoregressive Conditional Heteroskedasticity (GARCH) model.
/Users/rbrock/Archive/OwnersBox/venv/lib/python3.12/site-packages/statsforecast/models.py:5928: SyntaxWarning: invalid escape sequence '\e'
  """Autoregressive Conditional Heteroskedasticity (ARCH) model.
```
This is presumably caused by the [DeprecationWarning to SyntaxWarning change](https://docs.python.org/3/whatsnew/3.12.html#other-language-changes) introduced in Python 3.12. This should fix it; it seems the error was some $\LaTeX$ escape sequences that were improperly double-escaped in the source code. I created the pull request by find-and-replacing `\h`, `\s`, and `\e` with `\\h`, `\\s`, and `\\e` respectively.

### CODE REVIEW

**Comment by jmoralez** [comment]
Seems like we can just use raw strings for our docstrings, would you like to make that change @ravibrock?

**Comment by jmoralez** [comment]
Also, can you please export the changes to the source code? You can find a detailed guide [here](https://github.com/Nixtla/statsforecast/blob/main/CONTRIBUTING.md)

**Comment by ravibrock** [comment]
@jmoralez all the comments should be updated to raw strings but when I run `nbdev_export models.ipynb` (after running `pipx install nbdev`) I get the following error:
```
Traceback (most recent call last):
  File "/Users/ravibrock/.local/bin/nbdev_prepare", line 5, in <module>
    from nbdev.quarto import prepare
  File "/Users/ravibrock/.local/pipx/venvs/nbdev/lib/python3.12/site-packages/nbdev/__init__.py", line 3, in <module>
    from .doclinks import nbdev_export
  File "/Users/ravibrock/.local/pipx/venvs/nbdev/lib/python3.12/site-packages/nbdev/doclinks.py", line 17, in <module>
    import pkg_resources,importlib
ModuleNotFoundError: No module named 'pkg_resources'
```
Not sure why that is--never used nbdev before now. The changes should be pushed to the notebook, though.

**Comment by jmoralez** [comment]
I think there was a recent breaking change in setuptools 70, it should be fixed by downgrading (e.g. `pip install "setuptools<70"`), but I can run the export and push it here as well.

**Review by jmoralez — APPROVED** [review]
Thanks a lot! And thanks for also removing the unneeded escapes!

**Comment by ravibrock** [comment]
Happy to help!

**Pull request merged**
