### PR TITLE
config: CI, add python 3.12

### PR DESCRIPTION
**Pull request by westonplatter**
Adds python 3.12 to the CI matrix. Skips the ray tests since ray doesn't support python 3.12 yet.

### CODE REVIEW

**Comment by jmoralez** [comment]
Hey @westonplatter, thanks for the contribution. Can you please also add it in the following places?

https://github.com/Nixtla/statsforecast/blob/b61476e603e1fe7a681fee2ad3254130962ce1b7/.github/workflows/ci.yaml#L50
https://github.com/Nixtla/statsforecast/blob/b61476e603e1fe7a681fee2ad3254130962ce1b7/.github/workflows/ci.yaml#L75

**Comment by westonplatter** [comment]
@jmoralez thanks for pointing our the additional places where versions come about. Added 3.12 there too. Searched the rest of the codebase for `3.11` and didn't see other places.

**Comment by jmoralez** [comment]
Can you please remove these two lines:
https://github.com/Nixtla/statsforecast/blob/b61476e603e1fe7a681fee2ad3254130962ce1b7/dev/environment.yml#L5
https://github.com/Nixtla/statsforecast/blob/b61476e603e1fe7a681fee2ad3254130962ce1b7/dev/local_environment.yml#L5
I think that was for python 3.7

**Comment by jmoralez** [comment]
So now it's ray that [doesn't support python 3.12](https://github.com/ray-project/ray/blob/09abba26b5bf2707639bb637c208d062a47b46f6/python/setup.py#L30)

**Review by jmoralez — APPROVED** [review]

**Pull request merged**
